[WIP] Fix failing tests
ckeditor/ckeditor4-vue pull request #127
Opened 2021-12-01 12:23 UTC by sculpt0r

Closes #124

2021-12-07 14:36 UTC, jacekbogdanski approved these changes

2021-12-07 14:36 UTC, jacekbogdanski commented on tests/component.js
> +		props = {...props}
```suggestion
		props = { ...props }
```

2021-12-07 14:46 UTC, jacekbogdanski requested changes
I didn't notice it earlier but it looks like we lost 100% test coverage somehow. Could you take a look @sculpt0r ?
![image](https://user-images.githubusercontent.com/10279586/145050561-263fb619-e9b5-490e-9a2f-ba062f9350aa.png)

2021-12-07 14:46 UTC, jacekbogdanski commented on tests/integration.js
> +		return createComponent( { editorUrl: basePath + 'ckeditor.js' } ).then( (comp) => {
```suggestion
		return createComponent( { editorUrl: basePath + 'ckeditor.js' } ).then( ( comp ) => {
```

2021-12-07 14:46 UTC, jacekbogdanski commented on tests/integration.js
> +		});
```suggestion
		} );
```

2021-12-13 14:39 UTC, sculpt0r commented
The gap I coverage appears due to the fact - that now there is no editor created with empty config. Because I added `observableParent` to each config. I'll figure it out.

2021-12-14 11:14 UTC, sculpt0r commented
@jacekbogdanski 
- adjusted tests so after each test namespace clean up is made
- added test for creating editor with the default config. I put it at the end - so no other tests fail because of it. It doesn't look well... I left a comment above the test. However with #102 the tests will be touched again - so maybe it will be a good time to look at the tests with config again.

2022-01-04 09:33 UTC, jacekbogdanski approved these changes
Looks good 👍🏻 We can handle tests related to delayed initialization in the dedicated PR.

2022-01-04 09:33 UTC, merged